name: Build on upstream release

on:
  workflow_dispatch:
  release:
    types: [published]
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: proton-natpmp

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/linuxserver/docker-transmission.git
          git fetch upstream main

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # Or specify the directory containing your Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/transmission:proton-natpmp

      - name: Logout of Docker Hub
        uses: docker/logout-action@v2
